index_homepage:
    path:     /
    defaults: { _controller: IndexBundle:Default:index }

ani:
    path:     /animales/new
    defaults: { _controller: AnimalesBundle:Animales:new }

anunc:
    path:     /anuncios/new
    defaults: { _controller: AnunciosBundle:Anuncios:new }

index_p:
    path:     /index
    defaults: { _controller: IndexBundle:Default:indexp }
